version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://tishanw:tishanW98@books-store-mern.3tvmvhm.mongodb.net/file?retryWrites=true&w=majority

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
