# Use the official Node.js image
FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose the port that the app runs on
EXPOSE 5000

# Command to run the app
CMD [ "npm", "start" ]
